config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: 'public/homes#top'
  get 'admin' => 'admin/homes#top', as: 'admin'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'customers/confirm'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    patch 'customers/update_status'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
  end

  namespace :admin do
    resources :customers, only: [:edit, :index, :update, :show]
    resources :genres, only: [:edit, :create, :index, :update]
    resources :items, only: [:edit, :create, :index, :update, :show, :new]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  validates :name, :image, :price, :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    with_tax_price * amount
  end

  enum making_status: { production_not_allowed: 0, waiting_production: 1, production: 2, production_completed: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "You have created book successfully."
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
    
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @genre = @item.genre
      if @item.update(item_params)
        redirect_to admin_item_path(@item.id)
      else
        render :edit
      end

  end

  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details
  end

  def update
     @order = Order.find(params[:id])
     @order.update(order_params)
     redirect_to admin_order_path(@order.id)
     #order_details = @order.order_details
    # order_details.update(order_details_params)
    # redirect_to admin_order_path(@order.id)

  end

  private
  def order_params
    params.require(:order).permit(:status)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :reset_password_token])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-4 mt-4">
      <h4 style = "background-color: #d3d3d3;">
        <%=@customer.last_name %>
        <%=@customer.first_name %>
        さんの会員情報編集
      </h4>
    </div>
  </div>
  <% if @customer.errors.any? %>
    <%= @customer.errors.count %>errors prohibited this obj from being saved:
      <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
  <div class="row">
    <div class = "col-xl-8 mt-4">
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">会員ID</span>
        <%=@customer.id %>
      </div>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="customer_name">氏名</label>
        </div>
        <%= f.text_field :last_name ,class: "form-control last_name", style: "width: 30%;" %>
        <%= f.text_field :first_name ,class: "form-control first_name ml-5", style: "width: 30%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="customer_name_kana">フリガナ</label>
        </div>
        <%= f.text_field :last_name_kana ,class: "form-control last_name_kana", style: "width: 30%;" %>
        <%= f.text_field :first_name_kana ,class: "form-control first_name_kana ml-5", style: "width: 30%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="customer_postal_code">郵便番号</label>
        </div>
        <%= f.text_field :postal_code ,class: "form-control postal_code", style: "width: 30%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="customer_address">住所</label>
        </div>
        <%= f.text_field :address ,class: "form-control address", style: "width: 66%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="customer_telephone_number">電話番号</label>
        </div>
        <%= f.text_field :telephone_number ,class: "form-control telephone_number", style: "width: 30%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
        <label for="customer_email">メールアドレス</label>
        </div>
        <%= f.text_field :email ,class: "form-control email", style: "width: 30%;" %>
      </div>
      <div class="form-group">
        <label for="item_is_deleted">会員ステータス</label>

        <%= f.radio_button :is_deleted , false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted , true %>
        <%= f.label :is_deleted, "退会" %>

      </div>
      <div class="form-group text-center">
        <%= f.submit '変更を保存' ,class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-8 offset-xl-2 mt-4">
    <H4 style = "background-color: #d3d3d3; width: 15%">会員一覧</H4>
      <table class = "table mt-4">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td>
              <%= link_to admin_customer_path(customer.id) do %>
                <%= customer.last_name %>
                <%= customer.first_name %>
              <% end %>
            </td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
              <div class = "text-success">有効</div>
              <% else %>
              <div class = "text-secondary">退会</div>
              <% end %>
            </td>
          </tr>
          <% end %>
          <%= paginate @customers %>
        </tbody>
      </table>
     </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-4 offset-xl-2 mt-4">
      <h4 style = "background-color: #d3d3d3;">
        <%= @customer.last_name %>
        <%= @customer.first_name %>
        さんの会員詳細
      </h4>
      <div class="form-group d-flex align-items-center mt-5">
        <span class = "mr-5">会員ID</span>
        <%= @customer.id %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">氏名</span>
        <%= @customer.last_name %>
        <%= @customer.first_name %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">郵便番号</span>
        <%= @customer.postal_code %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">住所</span>
        <%= @customer.address %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">電話番号</span>
        <%= @customer.telephone_number %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">メールアドレス</span>
        <%= @customer.email %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">会員ステータス</span>
        <% if @customer.is_deleted == false %>
        <div class = "text-success">有効</div>
        <% else %>
        <div class = "text-secondary">退会</div>
        <% end %>
      </div>
      <div class="form-group d-flex align-items-center mt-5">
        <%= link_to edit_admin_customer_path(@customer.id) do %>
          <%= submit_tag '編集する' ,class: "btn btn-success mr-5" %>
        <% end %>
        <%= link_to admin_path do %>
          <%= submit_tag '注文履歴一覧を見る' ,class: "btn btn-primary ml-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>