config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: 'public/homes#top'
  get 'admin' => 'admin/homes#top', as: 'admin'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'customers/confirm'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    patch 'customers/update_status'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
  end

  namespace :admin do
    resources :customers, only: [:edit, :index, :update, :show]
    resources :genres, only: [:edit, :create, :index, :update]
    resources :items, only: [:edit, :create, :index, :update, :show, :new]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  validates :name, :image, :price, :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    with_tax_price * amount
  end

  enum making_status: { production_not_allowed: 0, waiting_production: 1, production: 2, production_completed: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "You have created book successfully."
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
    
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @genre = @item.genre
      if @item.update(item_params)
        redirect_to admin_item_path(@item.id)
      else
        render :edit
      end

  end

  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @customer = @order.customer
    @order_details = @order.order_details
  end

  def update
     @order = Order.find(params[:id])
     @order.update(order_params)
     redirect_to admin_order_path(@order.id)
     #order_details = @order.order_details
    # order_details.update(order_details_params)
    # redirect_to admin_order_path(@order.id)

  end

  private
  def order_params
    params.require(:order).permit(:status)
  end


end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :reset_password_token])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-6 offset-xl-2 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 30%;">ジャンル編集</h4>
      <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
        <div class="form-group d-flex align-items-center mt-5">
          <div style = "width: 20%;">
            <label for="genre_name">ジャンル名</label>
          </div>
          <%= f.text_field :name ,class: "form-control name", style: "width: 80%;" %>
        </div>
        <div class="form-group text-center mt-5">
          <%= f.submit '変更を保存' ,class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-10 offset-xl-1 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 25%;">ジャンル一覧・追加</h4>
      <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
        <div class="form-group d-flex align-items-center mt-4">
          <div style = "width: 20%;">
            <label for="genre_name">ジャンル名</label>
          </div>
          <%= f.text_field :name ,class: "form-control name mr-5", style: "width: 30%;" %>
          <%= f.submit '新規登録' ,class: "btn btn-success", style: "width: 30%;" %>
        </div>
      <% end %>
    </div>
    <div class = "col-xl-6 offset-xl-3">
      <table class = "table mt-4">
        <thead>
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td>
                <%= link_to edit_admin_genre_path(genre.id) do %>
                  <%= submit_tag '編集する' ,class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-4 offset-xl-3 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 30%;">商品編集</h4>
    </div>
    <div class = "col-xl-6 offset-xl-3">
      <% if @item.errors.any? %>
      <%= @item.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_with model: @item, url: admin_item_path, method: :patch do |f| %>
      <div class="form-group d-flex align-items-center mt-4">
        <div style = "width: 20%;">
          <label for="item_image">商品画像</label>
        </div>
        <%= f.file_field :image, class: "form-control-file image", style: "width: 80%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="item_name">商品名</label>
        </div>
        <%= f.text_field :name ,class: "form-control name", style: "width: 80%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="item_introduction">商品説明</label>
        </div>
        <%= f.text_area :introduction ,class: "form-control introduction", style: "width: 80%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="item_genre">ジャンル</label>
        </div>
        <%= f.select :genre_id, [ ["ケーキ", 1], ["プリン", 2],["キャンディ", 3],["焼き菓子", 4] ], prompt: "--選択してください--", style: "width: 80%;" %>
      </div>
      <div class="form-group d-flex align-items-center">
        <div style = "width: 20%;">
          <label for="item_price">税抜価格</label>
        </div>
        <%= f.text_field :price ,class: "form-control price", style: "width: 80%;" %>円
      </div>
      <div class="form-group">
        <label for="item_is_active">販売ステータス</label>
        <%= f.radio_button :is_active , true %>
        <%= f.label :is_active, "販売中" %>
        <%= f.radio_button :is_active , false %>
        <%= f.label :is_active, "販売停止中" %>
      </div>
      <div class = "text-center">
        <%= f.submit '変更を保存' ,class: "btn btn-success mt-3" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-10 offset-xl-1 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 15%;">商品一覧</h4>
      <div class="button-right"
        style="display: inline-block;text-align: right;width: 85%;">
        <%= link_to new_admin_item_path do %>
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
      <table class = "table">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
            <tr>
              <td><%= item.id %></td>
              <td>
                <%= link_to item.name, admin_item_path(item.id) %>
              </td>
              <td><%=item.price %></td>
              <td><%=item.genre.name %></td>
              <td>
                <% if item.is_active == true %>
                  <div class = "text-success">販売中</div>
                <% elsif item.is_active == false %>
                  販売停止中
                <% end %>
              </td>
            </tr>
          <% end %>

          <%= paginate @items %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-2 offset-xl-3 mt-4">
      <h4 style = "background-color: #d3d3d3;">商品新規登録</h4>
      <% if @item.errors.any? %>
      <%= @item.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
    <div class = "col-xl-6 offset-xl-3">
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <div class="form-group d-flex align-items-center mt-4">
          <div style = "width: 20%;">
            <label for="item_image">商品画像</label>
          </div>
          <%= f.file_field :image, class: "form-control-file image", style: "width: 80%;" %>
        </div>
        <div class="form-group d-flex align-items-center">
          <div style = "width: 20%;">
            <label for="item_name">商品名</label>
          </div>
          <%= f.text_field :name ,class: "form-control name", style: "width: 80%;" %>
        </div>
        <div class="form-group d-flex align-items-center">
          <div style = "width: 20%;">
            <label for="item_introduction">商品説明</label>
          </div>
          <%= f.text_area :introduction ,class: "form-control introduction", style: "width: 80%;" %>
        </div>
        <div class="form-group d-flex align-items-center">
          <div style = "width: 20%;">
            <label for="item_genre">ジャンル</label>
          </div>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, { prompt: "選択してください" } %>
        </div>
        <div class="form-group d-flex align-items-center">
          <div style = "width: 20%;">
            <label for="item_price">税抜価格</label>
          </div>
          <%= f.text_field :price ,class: "form-control price", style: "width: 80%;" %>円
        </div>
        <div class="form-group">
          <label for="item_is_active">販売ステータス</label>
          <%= f.radio_button :is_active , true %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active , false %>
          <%= f.label :is_active, "販売停止中" %>
        </div>
        <div class="form-group">
          <%= f.submit '新規登録' ,class: "btn btn-success" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-3 offset-xl-1 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 50%;">商品詳細</h4>
      <div class = "mt-4">
        <%= image_tag @item.image, :size => '200x200' %>
      </div>
    </div>
    <div class = "col-xl-5 offset-xl-1 mt-5">
      <table class = "table">
        <tr>
          <th>商品名</th>
          <td><%=@item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%=@item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%=@item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格(税抜価格)</th>
          <td>¥<%=@item.price %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active == true %>
              販売中
            <% elsif @item.is_active == false %>
              販売停止中
            <% end %>
          </td>
        </tr>
      </table>
      <%= link_to edit_admin_item_path(@item.id), class: "btn btn-success mt-3" do %>
        編集する
      <% end %>
    </div>
  </div>
<div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col-xl-4 mt-4">
      <h4 style = "background-color: #d3d3d3; width: 45%;">注文履歴詳細</h4>
    </div>
  </div>
  <div class="row">
    <div class = "col-xl-9 mt-4">
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">購入者</span>
        <%= link_to admin_customer_path(@customer.id) do %>
          <%= @order.name %>
        <% end %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">注文日</span>
        <%= @order.created_at %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">配送先</span>
        〒<%= @order.postal_code %>
        <%= @order.address %>
        <%= @order.name %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">支払方法</span>
        <%= @order.payment_method_i18n %>
      </div>
      <div class="form-group d-flex align-items-center">
        <span class = "mr-5">注文ステータス</span>
        <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
          <%= f.select :status,Order.statuses.keys.map{|k| [I18n.t("enums.order.status.#{k}"),k]} %>
          <%= f.submit '更新' ,class: "btn btn-success ml-5" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class = "col-xl-9">
      <table class = "table table-hover table-inverse">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.with_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.with_tax_price * order_detail.amount %></td>
            <td>
              <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), method: :patch do |f| %>
                <%= f.select :making_status,OrderDetail.making_statuses.keys.map{|k| [I18n.t("enums.order_detail.making_status.#{k}"),k]} %>
                <%= f.submit '更新' ,class: "btn btn-success ml-5" %>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class = "col-xl-3">
      <table class = "table table-hover table-inverse">
        <tr>
          <th>商品合計</th>
          <td><%= @order_details.sum(&:subtotal) %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.shopping_cost %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.total_payment %></td>
        </tr>
      </table>
    </div>
  </div>
</div>