config/routes.rb
Rails.application.routes.draw do
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  root to: 'public/homes#top'
  get 'admin' => 'admin/homes#top', as: 'admin'

  scope module: :public do
    get 'about' => 'homes#about', as: 'about'
    get 'customers/confirm'
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information' => 'customers#update'
    patch 'customers/update_status'
    delete 'cart_items/destroy_all'
    post 'orders/confirm'
    get 'orders/complete', as: 'complete'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :create, :destroy, :destroy_all, :update]
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
    resources :orders, only: [:index, :show, :new, :create]
  end

  namespace :admin do
    resources :customers, only: [:edit, :index, :update, :show]
    resources :genres, only: [:edit, :create, :index, :update]
    resources :items, only: [:edit, :create, :index, :update, :show, :new]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  belongs_to :genre
  has_many :cart_items, dependent: :destroy

  validates :name, :image, :price, :genre_id, presence: true

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_payment: 0, payment_confirmation: 1, production: 2, shipping_preparation: 3, shipped: 4}

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    with_tax_price * amount
  end

  enum making_status: { production_not_allowed: 0, waiting_production: 1, production: 2, production_completed: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    @orders = Order.page(params[:page])
    
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])

  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
     redirect_to admin_item_path(@item.id)
    else
     render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @genre = @item.genre
      if @item.update(item_params)
        redirect_to admin_item_path(@item.id)
      else
        render :edit
      end

  end

  private
  def item_params
    params.require(:item).permit(:image,:name,:introduction,:genre_id,:price,:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :encrypted_password, :reset_password_token])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <% if customer_signed_in? %>
          <a class="navbar-brand" href="/">
            <span>LOGO</span>
          </a>
          <div class = "navbar-brand text-center">
            ようこそ、<%= current_customer.last_name %>さん！
          </div>

          <% else %>
            <span class="navbar-brand">LOGO</span>
          <% end %>

          <% if admin_signed_in? %>
          <li>
            <%= link_to admin_items_path, class: 'nav-link text-light' do %>
              <span>商品一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
              <span>会員一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_path, class: 'nav-link text-light' do %>
              <span>注文履歴一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
              <span>ジャンル一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <span>ログアウト</span>
            <% end %>
          </li>
          <% elsif customer_signed_in? %>
          <li>
            <%= link_to customers_my_page_path, class: 'nav-link text-light' do %>
              <span>マイページ</span>
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light' do %>
              <span>商品一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path, class: 'nav-link text-light' do %>
              <span>カート</span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
              <span>ログアウト</span>
            <% end %>
          </li>
          <% else %>
          <li>
            <%= link_to about_path, class: 'nav-link text-light' do %>
              <span>About</span>
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: 'nav-link text-light' do %>
              <span>商品一覧</span>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
              <span>新規登録</span>
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
              <span>ログイン</span>
            <% end %>
          </li>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>